### PR TITLE
Print values in email with Twig extension using ValueExporter class

### LINKED ISSUE #2: All values in session as string
You asume all values in session are strings

```
File: exception.html.twig
Line: 30
```

### PR DESCRIPTION
**Pull request by mayeco**
The session may contain sensitive data 

Also this fix #2

### CODE REVIEW

**Comment by desarrolla2** [comment]
what do you think about add a configuration option to send session data on email and set false by default?

Do you want to implement this?

About that all session values are string, what do you thing about this.

``` php
        $items = $this->session->all();
        $sessionValues = [];
        foreach ($items as $key => $item) {
            if (!is_object($item)) {
                $sessionValues[$key] = (string)$item;
                continue;
            }
            if (method_exists($item, '__toString')) {
                $sessionValues[$key] = $item->__toString();
                continue;
            }
                $sessionValues[$key] = 'object';
        }
```

Regards

**Comment by mayeco** [comment]
Hi Daniel,

Look like Symfony print the session vars in the WebProfilerBundle

Look here:

```
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/table.html.twig
```

and the Twig Ext

```
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/WebProfilerBundle/Twig/WebProfilerExtension.php
```

and the Util class from HttKernel

```
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpKernel/DataCollector/Util/ValueExporter.php
```

I think we should do the same here... we can do a Twig Ext using the ValueExporter class, if you want I can change this PR and do it.

**Comment by desarrolla2** [comment]
Ok, looks great

sent from nexus 5

**Comment by mayeco** [comment]
It's done Daniel

image

Works for arrays, objects and scalar values., I think we should print the values for now maybe latter add the option for the session data, ok?

Fix #2

**Pull request merged**
